### ISSUE TITLE
RNG suggestions

### ISSUE THREAD

**Issue by tarcieri** [zkcrypto/group#10]
Some assorted nits about how this crate handles random number generation:

It seems like if `tests` were a cargo feature, this crate could depend upon `rand_core` instead of `rand` (optionally importing the latter when the `tests` feature is enabled). One fewer dependency would be nice.

Additionally, I'd suggest changing the `Group::random` method in the following way:

```
-    fn random<R: RngCore + ?Sized>(rng: &mut R) -> Self;
+    fn random(rng: impl CryptoRng + RngCore) -> Self;
```

Concretely this is:

1. `RngCore` is implemented for `&mut RngCore`, so you don't need to include `&mut` in the signature
2. Bound on `CryptoRng` in addition to `RngCore` (it seems the reason this isn't already this way is for `XorShiftRng`?)
3. Use `impl Trait` as syntactic sugar to remove the type parameter (IMO there's no cases where an explicit type parameter helps here, so removing it makes it easier to read)

**Comment by str4d** [comment]
These are all great suggestions!

Re: `CryptoRng`, @ebfull and I discussed it, and we can work around that bound for the built-in generic tests by wrapping `XorShiftRng` in a internal-only newtype on which we implement `CryptoRng`. For concrete group implementations, they can easily have a concrete internal `random(impl RngCore)` function that they call from `Group::random(impl RngCore + CryptoRng)`.

**Comment by str4d** [comment]
Hmm, we should make the `random` bounds both here and in `ff` consistent, but adding `CryptoRng` to `Field::random` would AFAICT break the use case in https://github.com/zkcrypto/ff/issues/13. I'm also not clear on whether this would need to be `fn random(rng: impl CryptoRng + RngCore + ?Sized) -> Self` in order to be interoperable with other `rand` APIs.

**Comment by tarcieri** [comment]
The `?Sized` bound is irrelevant if you pass a reference type, since all reference types are `Sized`

**Comment by str4d** [comment]
@hdevalence suggested using `foo<R: RngCore + CryptoRng>(mut rng: R)` instead of `foo(mut rng: impl RngCore + CryptoRng)`. Is there any clear or consistent approach to these APIs in existing cryptographic crates?

**Comment by tarcieri** [comment]
`mut rng` vs `rng` is irrelevant to the trait signature since it affects how the local argument is bound and therefore doesn’t need to be part of the signature.

Re: an explicit generic parameter versus the impl Trait sugar, IMO it’s a question of whether there’s a use case where you’d want to pass the generic parameter explicitly for whatever reason (e.g. turbofish). If there isn’t, impl Trait in the argument position makes the method signatures much more readable, IMO.

I feel like CSPRNGs are a case where the receiver just wants a `CryptoRng` and doesn’t care what it is, and that holds through the whole call chain until you get to an explicit type. But perhaps there’s a use case I haven’t thought of.

**Comment by burdges** [comment]
> Is there any clear or consistent approach to these APIs in existing cryptographic crates? 

Nope.  Aside from cryptography, I think `impl<'a,R: T+?Sized> T for &'a mut R` exists for `T` among `Iterator`, `RngCore`, etc. mostly because we lack syntactic sugar for `R: impl BorrowMut<impl T>`, due partially to `Borrow` vs `AsRef`.  We achieve 90% of `BorrowMut`s goodness this way, without the verbosity, but with some sanity price already paid by the rand developers.  ;)

You must reborrow occasionally when you've multiple calls into which you pass the `RngCore`, so maybe `R: &mut &mut &mut RealRng` under the hood.  We run into this minor hiccup more with `RngCore` than say `Iterator`, but overall still worthwhile.  I've no idea when if ever Rust/LLVM optimizes away those unnecessary `&mut`s, but if not then maybe should work on that since `Iterator` does this.  Any truly recursive algorithm wants `&mut R` of course, but they can do so easily enough.

**Comment by str4d** [comment]
> `mut rng` vs `rng` is irrelevant to the trait signature since it affects how the local argument is bound and therefore doesn’t need to be part of the signature

I agree in signature, but in practice every non-trivial implementation will need to use `mut rng`, so it's worth thinking about. Pretty much any implementation of `Group::random` for elliptic curves will need to do this:
```rust
fn random(mut rng: impl RngCore) -> Self {
    loop {
        let one_coordinate = SomeField::random(&mut rng);
        if can_derive_valid_point {
            break valid_point;
        }
    }
}
```

Given that the `&mut`-less APIs will almost all in practice be passed an `&mut` (either due to the caller having one, or needing to use its RNG more than once), I don't really see a reason to prefer one over the other. I _do_ understand the reasoning for `rng: impl RngCore` vs `<R: RngCore> rng: R`, so another alternative could be `rng: &mut impl RngCore`, but I haven't seen that suggested or used anywhere, so we probably shouldn't proliferate Yet Another Type Signature without good cause.

> Re: an explicit generic parameter versus the impl Trait sugar, IMO it’s a question of whether there’s a use case where you’d want to pass the generic parameter explicitly for whatever reason (e.g. turbofish).

The main use case I can think of is builder patterns, if you need to access the RNG during builder setup. But that's a concern that requires higher-level context, and at the level of `Field::random` and `Group::random` the returned value has no forseeable reason to ever store the RNG.

---

Given the above, for `Field::random` and `Group::random`, I'm currently leaning towards `rng: impl RngCore` over `<R: RngCore> rng: R` or `<R: RngCore> rng: &mut R`. @ebfull thoughts?

**Comment by ebfull** [comment]
I agree with doing `rng: impl RngCore`, and if we do `&mut R` (or `&mut impl RngCore`) it'll introduce the `?Sized` bound issues again anyway.
